version: 2

updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: '08:00'
      timezone: America/Campo_Grande
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      time: '08:15'
      timezone: America/Campo_Grande
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:30'
      timezone: America/Campo_Grande
    open-pull-requests-limit: 5
