// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";


const databaseUrl = env("DATABASE_URL");

if (!databaseUrl) {
  throw new Error("[CRITICAL] A variável de ambiente DATABASE_URL não foi definida no arquivo .env!");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl
  },
});
