export const UI_KEYS = {
  recipes: {
    page: 'recipes.page',
    headerTitle: 'recipes.header.title',
    headerSubtitle: 'recipes.header.subtitle',
    search: 'recipes.search',
    list: 'recipes.list',
    createAction: 'recipes.actions.create',
    card: 'recipes.card',
    cardStatus: 'recipes.card.status',
    cardBatchCost: 'recipes.card.batchCost',
    cardUnitCost: 'recipes.card.unitCost',
    cardYield: 'recipes.card.yield',
    createModal: 'recipes.modal.create',
    editModal: 'recipes.modal.edit',
    viewModal: 'recipes.modal.view',
    formProduct: 'recipes.form.product',
    formYield: 'recipes.form.yield',
    formIngredient: 'recipes.form.ingredient',
    formQuantity: 'recipes.form.quantity',
    formSubmit: 'recipes.form.submit',
    statusDialog: 'recipes.statusDialog',
    statusDialogTitle: 'recipes.statusDialog.title',
    statusDialogDescription: 'recipes.statusDialog.description',
    statusDialogCancel: 'recipes.statusDialog.cancel',
    statusDialogConfirm: 'recipes.statusDialog.confirm'
  },
  pricing: {
    page: 'pricing.page',
    header: 'pricing.header',
    subTabs: 'pricing.subTabs',
    panel: 'pricing.panel',
    settingsTab: 'pricing.settings',
    settingsOperationalTitle: 'pricing.settings.operational.title',
    settingsMarginsTitle: 'pricing.settings.margins.title',
    maxProductionCap: 'pricing.settings.maxProductionCap',
    marginCategoryA: 'pricing.settings.marginCategoryA',
    marginCategoryB: 'pricing.settings.marginCategoryB',
    marginCategoryC: 'pricing.settings.marginCategoryC',
    settingsSubmit: 'pricing.settings.submit',
    productsTab: 'pricing.products',
    productFinalPrice: 'pricing.products.finalPrice',
    productFixedCosts: 'pricing.products.includeFixedCosts',
    syncStatus: 'pricing.products.syncStatus',
    servicesPlaceholder: 'pricing.services.placeholder'
  },
  expenses: {
    page: 'expenses.page',
    header: 'expenses.header',
    syncStatus: 'expenses.syncStatus',
    totalBadge: 'expenses.totalBadge',
    historyAction: 'expenses.actions.history',
    subTabs: 'expenses.subTabs',
    search: 'expenses.search',
    table: 'expenses.table',
    nameInput: 'expenses.row.name',
    valueInput: 'expenses.row.value',
    valueTypeSelect: 'expenses.row.valueType',
    representation: 'expenses.row.representation',
    deleteAction: 'expenses.row.delete',
    historyModal: 'expenses.history.modal',
    historyTitle: 'expenses.history.title',
    historyVersion: 'expenses.history.version',
    historyClose: 'expenses.history.close'
  },
  agenda: {
    page: 'agenda.page',
    header: 'agenda.header',
    liveClock: 'agenda.header.liveClock',
    filters: 'agenda.filters',
    calendarAction: 'agenda.actions.calendar',
    statusFilter: 'agenda.filters.status',
    dateFilter: 'agenda.filters.date',
    list: 'agenda.list',
    card: 'agenda.card',
    cardTitle: 'agenda.card.title',
    cardStatus: 'agenda.card.status',
    cardSubStatus: 'agenda.card.subStatus',
    cardBalance: 'agenda.card.balance',
    createAction: 'agenda.actions.create',
    createModal: 'agenda.modal.create',
    wizardTitle: 'agenda.wizard.title',
    wizardStep: 'agenda.wizard.step',
    formTitle: 'agenda.form.title',
    formDate: 'agenda.form.date',
    formTime: 'agenda.form.time',
    formNotes: 'agenda.form.notes',
    formSubStatus: 'agenda.form.subStatus',
    editModal: 'agenda.modal.edit',
    editSubmit: 'agenda.form.submit',
    viewModal: 'agenda.modal.view',
    viewSubStatus: 'agenda.view.subStatus',
    calendar: 'agenda.calendar',
    calendarRangeAction: 'agenda.calendar.rangeAction',
    cancelDialog: 'agenda.dialog.cancel',
    cascadeModal: 'agenda.modal.cascade',
    cascadeOffset: 'agenda.cascade.offset',
    cascadeUnit: 'agenda.cascade.unit',
    cascadeSubmit: 'agenda.cascade.submit'
  }
} as const;

export type UiKey =
  | typeof UI_KEYS.recipes[keyof typeof UI_KEYS.recipes]
  | typeof UI_KEYS.pricing[keyof typeof UI_KEYS.pricing]
  | typeof UI_KEYS.expenses[keyof typeof UI_KEYS.expenses]
  | typeof UI_KEYS.agenda[keyof typeof UI_KEYS.agenda];
